<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFrameworks>
		net9.0-android;
		net9.0-ios;
		net9.0-browserwasm;
		net9.0-desktop;
		net9.0-windows10.0.22621.0;
	</TargetFrameworks>
    <IsPackable>true</IsPackable>
    <UnoSingleProject>true</UnoSingleProject>
    <OutputType>Library</OutputType>
    <!-- Ensures the .xr.xml files are generated in a proper layout folder -->
    <GenerateLibraryLayout>true</GenerateLibraryLayout>
    <Nullable>enable</Nullable>
    
	  <UnoFeatures>
		  SkiaRenderer;
	  </UnoFeatures>
  </PropertyGroup>

  <!--<PropertyGroup Condition="'$([MSBuild]::GetTargetPlatformIdentifier($(TargetFramework)))' == 'windows'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>-->

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.WinUI.Behaviors" />
  </ItemGroup>


  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <PackageId>WinUI.TableView</PackageId>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <Description>TableView/DataGrid control for WinUI.</Description>
    <PackageTags>WinUI, WinAppSDK, Windows, UNO, XAML, TableView, DataGrid</PackageTags>
    <Product>WinUI TableView Control</Product>
    <RepositoryUrl>https://github.com/w-ahmad/WinUI.TableView</RepositoryUrl>
    <PackageProjectUrl>https://github.com/w-ahmad/WinUI.TableView</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageOutputPath>$(MSBuildThisFileDirectory)..\artifacts\NuGet\$(Configuration)\</PackageOutputPath>
    <Authors>w-ahmad - https://github.com/w-ahmad</Authors>
  </PropertyGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Release'">
    <PackageReference Include="Microsoft.SourceLink.GitHub">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
